Basic User Interface branch
ABDELLANI-Youcef/React-Calculator pull request #2
Opened 2021-02-25 18:51 UTC by ABDELLANI-Youcef

In this Pull Request, I:
- created components director;
- created  App, Display, ButtonsPanel, Button stateless functional components
- added properties types for Display, Display, ButtonsPanel, Button;
- added Display, ButtonsPanel containing all necessary buttons on it to the page.

2021-02-25 19:58 UTC, Forison requested changes
## Status::Changes required❌

# 🙋‍♂️ Youcef

#### You have done a good job on this one, almost all the requirements for this project were met, however there are a few issues we have to address to get this project approved.

* [x] Check my comment below👇

#### That is it, kindly make the changes and submit a re-review💪.

#### Happy coding👨‍💻

Addo Forison

2021-02-25 19:58 UTC, Forison commented on src/components/App.js
> +    <div className="App">
* [ ] App has children components wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))

2021-02-25 19:58 UTC, Forison commented on src/components/Button.js
> +const Button = props => {
**[OPTIONAL]**
`const Button = ({name}) => {} ` will save you from writing line 4

2021-02-25 19:58 UTC, Forison commented on src/components/ButtonsPanel.js
> +    <div>
**[OPTIONAL]** 
* [ ] Why not store the button names in an array and loop over the array and render Button. Then each time you are rendering a button, you pass the button name as the prop to the button. 
`buttonNames.map(name=> <button name={name} />)`
All you go to do it to get the order of the name right. This gives a much cleaner code.

2021-02-25 22:01 UTC, ABDELLANI-Youcef commented
Thanks very much for the advice. I followed them;

2021-02-26 02:47 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: 
Hi @ABDELLANI-Youcef :hand: 
Great job on this milestone

Happy coding :computer: 
**Sérgio Torres**

2021-02-26 09:09 UTC, merged