Calculator Logic branch
ABDELLANI-Youcef/React-Calculator pull request #3
Opened 2021-02-26 10:42 UTC by ABDELLANI-Youcef

In this Pull Request I:
- added folder for the logic of the calculator;
- added calculate.js and operate.js files in the logic folder;
- implement the simple operations operate.js: addition, minus, multiplication, division, percentage;
- implement general logic in calculate.js;
- included calculating module in App.

2021-02-26 10:46 UTC, ABDELLANI-Youcef commented
I included the calculate function in the App component. In order not to have it as a function declared but not used error, I passed it as a property to the ButtonPanel component. Even that it is not used yet.

2021-02-26 18:38 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @ABDELLANI-Youcef, great job on this project :muscle: The following have been achieved:
- calculate.js is imported in the App Component :1st_place_medal: 
- README is professional :100: 
- PR has a title and a short summary :1st_place_medal: 
- Commit messages easy to understand :smile: 

However, there is a little issue with calculate and operate module. Kindly check the comments below and address it accordingly

Once this is resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-26 18:38 UTC, addod19 commented on src/logic/calculate.js
> +  let { total, next } = calculator;
The calculator object property contains 3 properties, total, next, and operation. Let us kindly fix it

2021-02-26 18:38 UTC, addod19 commented on src/logic/operate.js
> +  const first = new Big(numberOne);
numberOne, and numberTwo should be wrapped with Big class. Currently, we only have numberOne wrapped in Big class

2021-02-26 21:36 UTC, ABDELLANI-Youcef commented
Thanks very much for your reviews. I made the requested changes and I treated the case where the button name is a number.

2021-02-27 10:26 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @ABDELLANI-Youcef :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-02-27 10:52 UTC, merged